[package]
name = "chess"
version = "0.1.0"
authors = ["Roland Mueller <1357906+oerli@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.4"